### ISSUE TITLE
Lack of file issues

### ISSUE THREAD

**Issue by lisong-HNU** [vocdex/digit-depth#4]
Hello, there is an error in operation when I run 'python scripts/ros/depth_value_pub.py'.  No such file or directory:'/home/shuk/digits2/tactile-in-hand/inhandpy/local/Mike/mike.ckpt',  Can you help me  solve this problem？thank you.

**Comment by vocdex** [comment]
Hi,
Please change the model_path inside rgb_to_normal.yaml  in /config folder to your trained depth model.
As the model is specific to each DIGIT sensor, it is required to train the model. For reference, you can download and try this model here on [Google Drive](https://drive.google.com/file/d/16eHfKuiCW9MtMKA15SYUk6SYNnVPpiNs/view?usp=sharing)

**Comment by vocdex** [comment]
Closing this issue. Feel free to open if you have questions
