### ISSUE TITLE
Misunderstanding of gel_min_depth and max_depth config parameters

### ISSUE THREAD

**Issue by Jcastanyo** [vocdex/digit-depth#8]
Hi! First of all I wanted to congratulate you for your work, it is really amazing.

I wonder what the gel_min_depth and max_depth config parameters mean. In digit.yaml, I can see your values of ~20mm, but I don't really understand how the gel is able to deform this much. The thickness of the sensor is around 2-3 mm, so it seems impossible to deform 20mm. 

If you could guide me with these two parameters, I would appreciate it.

Thanks in advance.
Julio.

**Comment by vocdex** [comment]
Hi Julio!
It's been a while but if I remember correctly, gel_min_depth and max_depth are not the actual deformation of the gel. They are the distances from camera (bottom of the sensor) to deformed and undeformed gel. You can first try to measure these distances.
Hope it's helpful.

**Comment by Jcastanyo** [comment]
Hi, thanks for your quick answer.

I've managed to train the MLP and test it with a few images from my DIGIT sensor. However, the depth estimation is not correct when there is no contact applied to the sensor. Maybe you have experienced this issue and you can help or guide me to improve the quality of the depth estimation. 

I attach the training images, the cvs file, the digit.yaml, and a few examples of the depth estimation. In the examples you will see that the model estimates an initial depth but there is no contact applied in that area.

[images.zip](https://github.com/vocdex/digit-depth/files/12249306/images.zip)
[annotate.csv](http
![Captura de pantalla de 2023-08-03 11-
![Captura de pantalla de 2023-08-03 11-34-09](https://github.com/vocdex/digit-depth/assets/84505434/d8a6460d-c692-4092-aaf4-c3041d610a4b)
44-07](https://github.com/vocdex/digit-depth/assets/84505434/bd415527-f101-45d5-a6a9-4f67223e639d)
s://github.com/vocdex/digit-depth
![Captura de pantalla de 2023-08-03 11-38-20](https://github.com/vocdex/digit-depth/assets/84505434/33d31c6e-359b-4a10-8cab-429f3a722fab)
/files/12249308/annotate.csv)

**Comment by vocdex** [comment]
That seems strange to me. It's been a while since I calibrated the sensors myself and I no longer have access to one, so I cannot test it on my own.
I would suggest doing another annotation and playing around with the gel parameters in the config file. Also, I noticed you annotated more around 700 images. Usually, for me, abour 30-40 images were enough to get good depth estimation. So, maybe, please try to use only 40 images in training the MLP model.

**Comment by Jcastanyo** [comment]
Hi, I am using the label_data.py script to label the images. I was annotating several points of the same circunference, that is why there were lots of rows inside of the csv file. Now, I am labelling only the center and one point of the circunference. Is that the right way to do it? I am getting the same depth estimation. Which gel parameters can be changed?
Thanks in advance.
